name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ubuntu-minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: eessi/github-action-eessi@v3
    - name: Test EESSI
      run: |
        ml HDF5/1.14.3-gompi-2023b HDF5/1.14.3-gompi-2023b CMake/3.27.6-GCCcore-13.2.0
        cd build
        cmake ..
        make
      shell: bash
