name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ubuntu-minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: eessi/github-action-eessi@v3
    - name: Test EESSI
      run: |
        ml EESSI-extend/2023.06-easybuild
        eb build.eb --software-commit $GITHUB_SHA 
        cd build
        cmake ..
        make
        mpirun -np 4 ./hello_mpi_hdf5
        ./verify_hdf5
      shell: bash
